name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: yes
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          
          # languages stat
          plugin_languages: yes
          plugin_languages_ignored: 'Jupyter Notebook'
          plugin_languages_details: percentage
          
          # wakatime section
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_METRICS_TOKEN }}
          plugin_wakatime_user: AlimU
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          
          # leetcode section
          plugin_leetcode: yes
          plugin_leetcode_user: AlimU11
          plugin_leetcode_sections: solved, skills
          plugin_leetcode_ignored_skills: fundamental

          # lines
          # plugin_lines: yes
          # plugin_lines_sections: base, repositories, history
          
          # habits
          # plugin_habits: yes
          
          # repositories
          # plugin_repositories: yes
          # plugin_repositories_featured: Anime-Recommender, Pascal-Interpreter, Sber-Avtopodpiska, Dashboards
          
          config_order: base.header, base.repositories, languages, habits, wakatime, leetcode, repositories
